//! Mock backend for testing
//!
//! This backend simulates 3DGS training without requiring external tools
//! like COLMAP or actual GPU training. Used primarily in E2E tests.

use anyhow::Result;
use async_trait::async_trait;
use std::path::Path;
use tokio::fs;
use tracing::{debug, info};

use super::{BackendOutput, GaussianSplatBackend, TrainingConfig};

/// Mock backend that simulates training for testing
///
/// This backend:
/// - Quickly "trains" by sleeping for a short duration
/// - Generates minimal valid .ply and .splat files
/// - Returns realistic metadata without actual computation
///
/// Useful for:
/// - E2E testing without GPU requirements
/// - CI/CD pipelines
/// - Integration testing
#[derive(Debug)]
pub struct MockBackend {
    /// Simulated processing time in milliseconds
    processing_time_ms: u64,
}

impl MockBackend {
    /// Create a new mock backend with default settings
    pub fn new() -> Self {
        Self {
            processing_time_ms: 100, // Fast for tests
        }
    }

    /// Create a mock backend with custom processing time
    pub fn with_processing_time(processing_time_ms: u64) -> Self {
        Self {
            processing_time_ms,
        }
    }

    /// Generate a minimal valid PLY file
    async fn generate_ply(path: &Path, gaussian_count: usize) -> Result<()> {
        let ply_content = format!(
            r#"ply
format ascii 1.0
comment 3DGS model generated by mock backend
element vertex {}
property float x
property float y
property float z
property float nx
property float ny
property float nz
property uchar red
property uchar green
property uchar blue
end_header
"#,
            gaussian_count
        );

        // Generate some random-ish vertex data
        let mut vertex_data = String::new();
        for i in 0..gaussian_count.min(1000) {
            // Limit to 1000 for speed
            let x = (i as f32 * 0.1) % 10.0 - 5.0;
            let y = (i as f32 * 0.2) % 10.0 - 5.0;
            let z = (i as f32 * 0.15) % 10.0 - 5.0;
            let r = (i % 256) as u8;
            let g = ((i * 2) % 256) as u8;
            let b = ((i * 3) % 256) as u8;

            vertex_data.push_str(&format!(
                "{:.3} {:.3} {:.3} 0.0 0.0 1.0 {} {} {}\n",
                x, y, z, r, g, b
            ));
        }

        fs::write(path, format!("{}{}", ply_content, vertex_data)).await?;

        Ok(())
    }

    /// Generate a valid .splat file in the standard antimatter15/splat format.
    ///
    /// Each Gaussian is exactly 32 bytes (no header):
    ///   - position: 3× f32 (12 bytes)
    ///   - scale:    3× f32 (12 bytes)
    ///   - color:    4× u8  RGBA (4 bytes)
    ///   - rotation: 4× u8  quaternion (4 bytes)
    async fn generate_splat(path: &Path, gaussian_count: usize) -> Result<()> {
        let count = gaussian_count.min(1000);
        let mut data = Vec::with_capacity(count * 32);

        for i in 0..count {
            // Position (3× f32 = 12 bytes)
            let x = (i as f32 * 0.1) % 10.0 - 5.0;
            let y = (i as f32 * 0.2) % 10.0 - 5.0;
            let z = (i as f32 * 0.15) % 10.0 - 5.0;
            data.extend_from_slice(&x.to_le_bytes());
            data.extend_from_slice(&y.to_le_bytes());
            data.extend_from_slice(&z.to_le_bytes());

            // Scale (3× f32 = 12 bytes)
            let scale: f32 = 0.01;
            data.extend_from_slice(&scale.to_le_bytes());
            data.extend_from_slice(&scale.to_le_bytes());
            data.extend_from_slice(&scale.to_le_bytes());

            // Color RGBA (4× u8 = 4 bytes)
            data.push((i % 256) as u8);
            data.push(((i * 2) % 256) as u8);
            data.push(((i * 3) % 256) as u8);
            data.push(255); // Alpha

            // Rotation quaternion (4× u8 = 4 bytes, 128 = 0.0 in normalized form)
            data.push(255); // w ≈ 1.0 (identity rotation)
            data.push(128); // x ≈ 0.0
            data.push(128); // y ≈ 0.0
            data.push(128); // z ≈ 0.0
        }

        fs::write(path, data).await?;

        Ok(())
    }
}

impl Default for MockBackend {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl GaussianSplatBackend for MockBackend {
    async fn train(
        &self,
        frames: &[&Path],
        _config: &TrainingConfig,
    ) -> Result<BackendOutput> {
        info!(
            frame_count = frames.len(),
            "Mock backend: simulating training"
        );

        // Validate frames is not empty (realistic check)
        if frames.is_empty() {
            anyhow::bail!("Cannot train with zero frames");
        }

        // Validate frames exist
        for frame in frames {
            if !frame.exists() {
                anyhow::bail!("Frame not found: {}", frame.display());
            }
        }

        // Simulate processing time
        if self.processing_time_ms > 0 {
            debug!(
                duration_ms = self.processing_time_ms,
                "Simulating training delay"
            );
            tokio::time::sleep(tokio::time::Duration::from_millis(self.processing_time_ms)).await;
        }

        // Create mock output
        let gaussian_count = frames.len() * 1000; // Simulate ~1000 gaussians per frame

        // Create a mock model file in temp directory
        let model_path = std::env::temp_dir().join(format!("mock_checkpoint_{}.pth", uuid::Uuid::new_v4()));
        
        // Write a minimal mock checkpoint file
        let mock_checkpoint_data = format!(
            "{{\"version\":\"1.0\",\"backend\":\"mock\",\"gaussian_count\":{},\"iterations\":1000}}",
            gaussian_count
        );
        fs::write(&model_path, mock_checkpoint_data.as_bytes()).await?;

        let mut output = BackendOutput::new(
            model_path,
            1000, // Simulated iterations
            "mock".to_string(),
        );

        output.final_loss = Some(0.0015); // Realistic loss value
        output.gaussian_count = Some(gaussian_count);

        output.metadata.training_time_secs = Some((self.processing_time_ms as f64) / 1000.0);
        output.metadata.backend_version = Some("1.0.0-mock".to_string());
        output.metadata.gpu_device = Some("mock-cpu".to_string());

        info!(
            gaussian_count = gaussian_count,
            iterations = output.iterations_completed,
            model_path = %output.model_path.display(),
            "Mock backend: training complete"
        );

        Ok(output)
    }

    async fn export_ply(&self, output: &BackendOutput, path: &Path) -> Result<()> {
        let path_str = path.display().to_string();
        info!(path = %path_str, "Mock backend: exporting PLY");

        // Create parent directory if needed
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).await?;
        }

        let gaussian_count = output.gaussian_count.unwrap_or(100_000);
        Self::generate_ply(path, gaussian_count).await?;

        let size_bytes = fs::metadata(path).await?.len();
        debug!(
            path = %path_str,
            size_bytes = size_bytes,
            "PLY export complete"
        );

        Ok(())
    }

    async fn export_splat(&self, output: &BackendOutput, path: &Path) -> Result<()> {
        let path_str = path.display().to_string();
        info!(path = %path_str, "Mock backend: exporting SPLAT");

        // Create parent directory if needed
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).await?;
        }

        let gaussian_count = output.gaussian_count.unwrap_or(100_000);
        Self::generate_splat(path, gaussian_count).await?;

        let size_bytes = fs::metadata(path).await?.len();
        debug!(
            path = %path_str,
            size_bytes = size_bytes,
            "SPLAT export complete"
        );

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;
    use tempfile::TempDir;

    #[tokio::test]
    async fn test_mock_backend_train() {
        let temp = TempDir::new().unwrap();
        let backend = MockBackend::new();

        // Create test frames
        let frame1 = temp.path().join("frame1.jpg");
        let frame2 = temp.path().join("frame2.jpg");
        fs::write(&frame1, b"fake image data").await.unwrap();
        fs::write(&frame2, b"fake image data").await.unwrap();

        let frames: Vec<&Path> = vec![frame1.as_path(), frame2.as_path()];
        let config = TrainingConfig::default();

        let output = backend.train(&frames, &config).await.unwrap();

        assert_eq!(output.metadata.backend_name, "mock");
        assert_eq!(output.iterations_completed, 1000);
        assert!(output.gaussian_count.is_some());
        assert!(output.final_loss.is_some());
    }

    #[tokio::test]
    async fn test_mock_backend_export_ply() {
        let temp = TempDir::new().unwrap();
        let backend = MockBackend::new();

        let mut output = BackendOutput::new(
            PathBuf::from("/tmp/mock.pth"),
            1000,
            "mock".to_string(),
        );
        output.gaussian_count = Some(500);

        let ply_path = temp.path().join("output.ply");
        backend.export_ply(&output, &ply_path).await.unwrap();

        assert!(ply_path.exists());

        let content = fs::read_to_string(&ply_path).await.unwrap();
        assert!(content.contains("ply"));
        assert!(content.contains("format ascii 1.0"));
        assert!(content.contains("element vertex"));
    }

    #[tokio::test]
    async fn test_mock_backend_export_splat() {
        let temp = TempDir::new().unwrap();
        let backend = MockBackend::new();

        let mut output = BackendOutput::new(
            PathBuf::from("/tmp/mock.pth"),
            1000,
            "mock".to_string(),
        );
        output.gaussian_count = Some(500);

        let splat_path = temp.path().join("output.splat");
        backend.export_splat(&output, &splat_path).await.unwrap();

        assert!(splat_path.exists());

        let content = fs::read(&splat_path).await.unwrap();
        // Standard .splat: no header, each gaussian is 32 bytes
        assert_eq!(content.len() % 32, 0, "File size must be a multiple of 32 bytes");
        assert!(content.len() > 0, "Has some data");
    }

    #[tokio::test]
    async fn test_mock_backend_nonexistent_frame() {
        let backend = MockBackend::new();
        let fake_frame = PathBuf::from("/nonexistent/frame.jpg");
        let frames: Vec<&Path> = vec![fake_frame.as_path()];
        let config = TrainingConfig::default();

        let result = backend.train(&frames, &config).await;
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("Frame not found"));
    }

    #[tokio::test]
    async fn test_mock_backend_custom_processing_time() {
        let backend = MockBackend::with_processing_time(50);

        let temp = TempDir::new().unwrap();
        let frame = temp.path().join("frame.jpg");
        fs::write(&frame, b"fake").await.unwrap();

        let frames: Vec<&Path> = vec![frame.as_path()];
        let config = TrainingConfig::default();

        let start = std::time::Instant::now();
        backend.train(&frames, &config).await.unwrap();
        let duration = start.elapsed();

        assert!(duration.as_millis() >= 50);
        assert!(duration.as_millis() < 200); // Should be fast
    }
}
